---
# Docker Supported OS:
#   * Debian: https://docs.docker.com/engine/install/debian/
#   * Ubuntu: https://docs.docker.com/engine/install/ubuntu/
- name: install OS pkg deps
  become: yes
  become_user: root
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: '{{ docker_engine_package_state | default("present") }}'
- name: add apt key
  become: yes
  become_user: root
  apt_key:
    url: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'
    id: '{{ docker_engine_apt_key_id }}'
    state: present

- name: add apt repository
  become: yes
  become_user: root
  apt_repository:
    repo: 'deb [arch={{ docker_engine_apt_repository_deb_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
    filename: docker-ce
    state: present

- name: install docker packages
  become: yes
  become_user: root
  apt:
    pkg:
      - docker-ce # {{ if docker_engine_version defined }}-{{ docker_engine_version }}{{ end }}
      # - docker-ce-cli
      - containerd.io
    state: '{{ docker_engine_package_state | default("present") }}'