---
# instructions per https://docs.docker.com/install/linux/docker-ce/debian/
- name: add apt key
  become: yes
  become_user: root
  apt_key:
    url: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
- name: add apt repository
  become: yes
  become_user: root
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
    filename: docker-ce
    state: present
- include_tasks: os-pkgs.yml
