---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- include_tasks: '{{ docker_engine_installer }}.yml'
- name: start/enable docker
  become: yes
  become_user: root
  when: docker_engine_manage_service
  service:
    name: docker
    state: '{{ docker_engine_state }}'
    enabled: '{{ docker_engine_enabled }}'
