---
# ArchLinux Installation Support: https://wiki.archlinux.org/index.php/Docker#Installation
- name: install docker
  become: yes
  become_user: root
  pacman:
    name: '{{ docker_engine_os_pkgs }}'
    state: '{{ docker_engine_package_state | default("present") }}'
