---
# instructions per https://docs.docker.com/install/linux/docker-ce/ubuntu/
- name: install OS pkg deps
  become: yes
  become_user: root
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: '{{ docker_engine_package_state | default("present") }}'
- name: add apt key
  become: yes
  become_user: root
  apt_key:
    url: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
- name: add apt repository
  become: yes
  become_user: root
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
    filename: docker-ce
    state: present
- name: install docker packages
  become: yes
  become_user: root
  package:
    name: '{{ docker_engine_pkgs }}'
    state: '{{ docker_engine_package_state | default("present") }}'
