---
# Docker Supported OS:
#   * CentOS: https://docs.docker.com/engine/install/centos/
#   * Fedora
- name: set yum config facts
  set_fact:
    yum_repository_os_distribution_base: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}'
    yum_repository_os_distribution_gpgkey: '{{ yum_repository_os_distribution_base }}/gpg'

- name: add docker-ce-stable repo
  become: yes
  become_user: root
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: '{{ yum_repository_os_distribution_base }}/$releasever/$basearch/stable'
    enabled: yes
    gpgcheck: yes
    gpgkey: '{{ yum_repository_os_distribution_gpgkey }}'

- name: add docker-ce-stable-debuginfo repo
  become: yes
  become_user: root
  yum_repository:
    name: docker-ce-stable-debuginfo
    description: Docker CE Stable - Debuginfo $basearch
    baseurl: '{{ yum_repository_os_distribution_base }}/$releasever/debug-$basearch/stable'
    enabled: no
    gpgcheck: yes
    gpgkey: {{ yum_repository_os_distribution_gpgkey }}

- name: add docker-ce-stable-source repo
  become: yes
  become_user: root
  yum_repository:
    name: docker-ce-stable-source
    description: Docker CE Stable - Sources
    baseurl: '{{ yum_repository_os_distribution_base }}/$releasever/source/stable'
    enabled: no
    gpgcheck: yes
    gpgkey: {{ yum_repository_os_distribution_gpgkey }}

- name: add docker-ce-edge repo
  become: yes
  become_user: root
  yum_repository:
    name: docker-ce-edge
    description: Docker CE Edge - $basearch
    baseurl: '{{ yum_repository_os_distribution_base }}/$releasever/$basearch/edge'
    enabled: no
    gpgcheck: yes
    gpgkey: {{ yum_repository_os_distribution_gpgkey }}

- name: add docker-ce-edge-debuginfo repo
  become: yes
  become_user: root
  yum_repository:
    name: docker-ce-edge-debuginfo
    description: Docker CE Edge - Debuginfo $basearch
    baseurl: '{{ yum_repository_os_distribution_base }}/$releasever/debug-$basearch/edge'
    enabled: no
    gpgcheck: yes
    gpgkey: {{ yum_repository_os_distribution_gpgkey }}

- name: add docker-ce-edge-source repo
  become: yes
  become_user: root
  yum_repository:
    name: docker-ce-edge-source
    description: Docker CE Edge - Sources
    baseurl: '{{ yum_repository_os_distribution_base }}/$releasever/source/edge'
    enabled: no
    gpgcheck: yes
    gpgkey: {{ yum_repository_os_distribution_gpgkey }}

- name: add docker-ce-test repo
  become: yes
  become_user: root
  yum_repository:
    name: docker-ce-test
    description: Docker CE Test - $basearch
    baseurl: '{{ yum_repository_os_distribution_base }}/$releasever/$basearch/test'
    enabled: no
    gpgcheck: yes
    gpgkey: {{ yum_repository_os_distribution_gpgkey }}

- name: add docker-ce-test-debuginfo repo
  become: yes
  become_user: root
  yum_repository:
    name: docker-ce-test-debuginfo
    description: Docker CE Test - Debuginfo $basearch
    baseurl: '{{ yum_repository_os_distribution_base }}/$releasever/debug-$basearch/test'
    enabled: no
    gpgcheck: yes
    gpgkey: {{ yum_repository_os_distribution_gpgkey }}

- name: add docker-ce-test-source repo
  become: yes
  become_user: root
  yum_repository:
    name: docker-ce-test-source
    description: Docker CE Test - Sources
    baseurl: '{{ yum_repository_os_distribution_base }}/$releasever/source/test'
    enabled: no
    gpgcheck: yes
    gpgkey: {{ yum_repository_os_distribution_gpgkey }}

- name: add docker-ce-nightly repo
  become: yes
  become_user: root
  yum_repository:
    name: docker-ce-nightly
    description: Docker CE Nightly - $basearch
    baseurl: '{{ yum_repository_os_distribution_base }}/$releasever/$basearch/nightly'
    enabled: no
    gpgcheck: yes
    gpgkey: {{ yum_repository_os_distribution_gpgkey }}

- name: add docker-ce-nightly-debuginfo repo
  become: yes
  become_user: root
  yum_repository:
    name: docker-ce-nightly-debuginfo
    description: Docker CE Nightly - Debuginfo $basearch
    baseurl: '{{ yum_repository_os_distribution_base }}/$releasever/debug-$basearch/nightly'
    enabled: no
    gpgcheck: yes
    gpgkey: {{ yum_repository_os_distribution_gpgkey }}

- name: add docker-ce-nightly-source repo
  become: yes
  become_user: root
  yum_repository:
    name: docker-ce-nightly-source
    description: Docker CE Nightly - Sources
    baseurl: '{{ yum_repository_os_distribution_base }}/$releasever/source/nightly'
    enabled: no
    gpgcheck: yes
    gpgkey: {{ yum_repository_os_distribution_gpgkey }}

# Make Generic Potentially
- name: install docker-engine via yum
  become: yes
  become_user: root
  yum:
    name: '{{ item }}{% if docker_engine_version is defined %}-{{ docker_engine_version }}{% endif %}'
    state: '{{ docker_engine_package_state | default("present") }}'
  with_items: '{{ docker_engine_os_pkgs }}'
